app:
  datasource:
    main:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/accommodation
      username: user
      password: 'password'
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always

spring:
  influx:
    url: http://localhost:8086
    token: FoqQS9O-03yn88wGXYolENm-L2OfzOSXDUBwjWS8fg3CPhE6Lo0hfVpFBVD4mUEoDlGF4nC6IPfyLAc4gTxcrw==
    username: admin
    password: password
    bucket: accommodation1
    org: Trading212

google:
  maps:
    key: AIzaSyB1XS6FJb5bMEV9-cxabQjHctcfMtUyVW0

application:
  security:
    jwt:
      secret-key: WSVo2B3unbW0ctyjLpyRS3VYWX+S9zosGt2/IBk7n4ERB9loLLJhsfDPPIHoyBFJ
      expiration: 86400000 # a day